version: '3.5'


services:
  tictactoe-front:
    container_name: tictactoe-front
    build:
      context: .
    ports:
        - 3000:3000
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
